version: '3'
services:
  da-house-rocket:
    image: da-house-rocket
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./dashboard.py:/dashboard.py
      - ./kc_house_data.csv:/kc_house_data.csv
    command: ["streamlit", "run", "dashboard.py"]
