version: '3'
services:
  da-house-rocket:
    image: da-house-rocket
    build: .
    ports:
      - "8502:8501"
    volumes:
      - ./app:/app
      - ./app/dataset:/app/dataset
    command: ["streamlit", "run", "dashboard.py"]
